name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add C++ build tools to PATH
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: make
      run: .\make.bat
